package presentacion.controlador;

public enum Evento {

    // VISTAS GENERALES
    VISTA_PRINCIPAL,

    // MODELO
    VISTA_MODELO,
    
    ALTA_MODELO, 
    VISTA_ALTA_MODELO, 
    VISTA_EXITO_ALTA_MODELO, 
    VISTA_FALLO_ALTA_MODELO,

    BAJA_MODELO, 
    VISTA_BAJA_MODELO, 
    VISTA_EXITO_BAJA_MODELO, 
    VISTA_FALLO_BAJA_MODELO,

    CONSULTAR_MODELO_POR_ID,  
    VISTA_CONSULTAR_MODELO_POR_ID, 
    VISTA_RESULTADO_CONSULTAR_MODELO_POR_ID,

    CONSULTAR_TODOS_MODELOS,  
    VISTA_RESULTADO_CONSULTAR_TODOS_MODELOS,

    MODIFICAR_MODELO, 
    VISTA_MODIFICAR_MODELO, 
    VISTA_EXITO_MODIFICAR_MODELO, 
    VISTA_FALLO_MODIFICAR_MODELO,

    VINCULAR_MODELO, 
    VISTA_VINCULAR_MODELO, 
    VISTA_EXITO_VINCULAR_MODELO, 
    VISTA_FALLO_VINCULAR_MODELO,

    DESVINCULAR_MODELO, 
    VISTA_DESVINCULAR_MODELO,
    VISTA_EXITO_DESVINCULAR_MODELO, 
    VISTA_FALLO_DESVINCULAR_MODELO,
    
    CONSULTAR_MODELOS_POR_AEROLINEA,  
    VISTA_CONSULTAR_MODELOS_POR_AEROLINEA, 
    VISTA_RESULTADO_CONSULTAR_MODELOS_POR_AEROLINEA,

    // AVIÓN
    VISTA_AVION,
    
    ALTA_AVION, 
    VISTA_ALTA_AVION, 
    VISTA_EXITO_ALTA_AVION, 
    VISTA_FALLO_ALTA_AVION,

    BAJA_AVION, 
    VISTA_BAJA_AVION, 
    VISTA_EXITO_BAJA_AVION, 
    VISTA_FALLO_BAJA_AVION,

    CONSULTAR_AVION_POR_ID, 
    VISTA_CONSULTAR_AVION_POR_ID, 
    VISTA_RESULTADO_CONSULTAR_AVION_POR_ID,

    CONSULTAR_TODOS_AVIONES, 
    VISTA_CONSULTAR_TODOS_AVIONES,

    MODIFICAR_AVION, 
    VISTA_MODIFICAR_AVION, 
    VISTA_EXITO_MODIFICAR_AVION, 
    VISTA_FALLO_MODIFICAR_AVION,

    CONSULTAR_AVIONES_POR_MODELO, 
    VISTA_CONSULTAR_AVIONES_POR_MODELO,
    VISTA_RESULTADO_CONSULTAR_AVIONES_POR_MODELO,

    CONSULTAR_AVIONES_POR_AEROLINEA, 
    VISTA_CONSULTAR_AVIONES_POR_AEROLINEA,
    VISTA_RESULTADO_CONSULTAR_AVIONES_POR_AEROLINEA,

    CONSULTAR_AVIONES_POR_HANGAR, 
    VISTA_CONSULTAR_AVIONES_POR_HANGAR,
    VISTA_RESULTADO_CONSULTAR_AVIONES_POR_HANGAR,

    CONSULTAR_AVIONES_DE_AEROLINEA_POR_HANGAR, //TODO PREGUNTAR A ANTONIO
    VISTA_CONSULTAR_AVIONES_DE_AEROLINEA_POR_HANGAR,
    VISTA_RESULTADO_CONSULTAR_AVIONES_DE_AEROLINEA_POR_HANGAR,

    // AEROLÍNEA
    VISTA_AEROLINEA,
    
    ALTA_AEROLINEA, 
    VISTA_ALTA_AEROLINEA, 
    VISTA_EXITO_ALTA_AEROLINEA, 
    VISTA_FALLO_ALTA_AEROLINEA,

    BAJA_AEROLINEA, 
    VISTA_BAJA_AEROLINEA, 
    VISTA_EXITO_BAJA_AEROLINEA, 
    VISTA_FALLO_BAJA_AEROLINEA,

    CONSULTAR_AEROLINEA_POR_ID, 
    VISTA_CONSULTAR_AEROLINEA_POR_ID, 
    VISTA_RESULTADO_CONSULTAR_AEROLINEA_POR_ID,

    CONSULTAR_TODAS_AEROLINEAS, 
    VISTA_RESULTADO_CONSULTAR_TODAS_AEROLINEAS,

    MODIFICAR_AEROLINEA, 
    VISTA_MODIFICAR_AEROLINEA, 
    VISTA_EXITO_MODIFICAR_AEROLINEA, 
    VISTA_FALLO_MODIFICAR_AEROLINEA,
    
    CONSULTAR_AEROLINEAS_POR_MODELO, 
    VISTA_CONSULTAR_AEROLINEAS_POR_MODELO, 
    VISTA_RESULTADO_CONSULTAR_AEROLINEAS_POR_MODELO,

    // CONTRATO
    VISTA_CONTRATO,
    
    ABRIR_CONTRATO, 
    VISTA_ABRIR_CONTRATO, 
    VISTA_EXITO_ABRIR_CONTRATO, 
    VISTA_FALLO_ABRIR_CONTRATO,
    
    ANYADIR_HANGAR_AL_CONTRATO, 
    VISTA_ANYADIR_HANGAR_AL_CONTRATO, 
    VISTA_EXITO_ANYADIR_HANGAR_AL_CONTRATO, 
    VISTA_FALLO_ANYADIR_HANGAR_AL_CONTRATO,

    CERRAR_CONTRATO, //TODO PREGUNTAR A JAVI
    VISTA_CERRAR_CONTRATO, 
    VISTA_EXITO_CERRAR_CONTRATO, 
    VISTA_FALLO_CERRAR_CONTRATO,

    CONSULTAR_CONTRATO_POR_ID, 
    VISTA_CONSULTAR_CONTRATO_POR_ID, 
    VISTA_RESULTADO_CONSULTAR_CONTRATO_POR_ID,

    CONSULTAR_TODOS_CONTRATOS, 
    VISTA_CONSULTAR_TODOS_CONTRATOS,

    MODIFICAR_CONTRATO, 
    VISTA_MODIFICAR_CONTRATO, 
    VISTA_EXITO_MODIFICAR_CONTRATO, 
    VISTA_FALLO_MODIFICAR_CONTRATO,

    MODIFICAR_LINEA_CONTRATO, 
    VISTA_MODIFICAR_LINEA_CONTRATO, 
    VISTA_EXITO_MODIFICAR_LINEA_CONTRATO, 
    VISTA_FALLO_MODIFICAR_LINEA_CONTRATO,

    CONSULTAR_CONTRATOS_POR_AEROLINEA, 
    VISTA_CONSULTAR_CONTRATOS_POR_AEROLINEA,
    VISTA_RESULTADO_CONSULTAR_CONTRATOS_POR_AEROLINEA, 
    
    CONSULTAR_CONTRATOS_POR_AEROLINEA_PRECIO_Y_DURACION, 
    VISTA_CONSULTAR_CONTRATOS_POR_AEROLINEA_PRECIO_Y_DURACION,
    VISTA_RESULTADO_CONSULTAR_CONTRATOS_POR_AEROLINEA_PRECIO_Y_DURACION, 

    // HANGAR
    VISTA_HANGAR,
    
    ALTA_HANGAR, 
    VISTA_ALTA_HANGAR, 
    VISTA_EXITO_ALTA_HANGAR, 
    VISTA_FALLO_ALTA_HANGAR,

    BAJA_HANGAR, 
    VISTA_BAJA_HANGAR, 
    VISTA_EXITO_BAJA_HANGAR, 
    VISTA_FALLO_BAJA_HANGAR,

    CONSULTAR_HANGAR_POR_ID, 
    VISTA_CONSULTAR_HANGAR_POR_ID, 
    VISTA_RESULTADO_CONSULTAR_HANGAR_POR_ID,

    CONSULTAR_TODOS_HANGARES, 
    VISTA_RESULTADO_CONSULTAR_TODOS_LOS_HANGARES,

    MODIFICAR_HANGAR, 
    VISTA_MODIFICAR_HANGAR, 
    VISTA_EXITO_MODIFICAR_HANGAR, 
    VISTA_FALLO_MODIFICAR_HANGAR,

    CONSULTAR_HANGARES_POR_PERSONAL, 
    VISTA_CONSULTAR_HANGARES_POR_PERSONAL, 
    VISTA_RESULTADO_CONSULTAR_HANGARES_POR_PERSONAL,

    // PERSONAL
    VISTA_PERSONAL,
    
    ALTA_PERSONAL, 
    VISTA_ALTA_PERSONAL, 
    VISTA_EXITO_ALTA_PERSONAL, 
    VISTA_FALLO_ALTA_PERSONAL,

    BAJA_PERSONAL, 
    VISTA_BAJA_PERSONAL, 
    VISTA_EXITO_BAJA_PERSONAL, 
    VISTA_FALLO_BAJA_PERSONAL,

    VINCULAR_PERSONAL, 
    VISTA_VINCULAR_PERSONAL, 
    VISTA_EXITO_VINCULAR_PERSONAL, 
    VISTA_FALLO_VINCULAR_PERSONAL,

    DESVINCULAR_PERSONAL, 
    VISTA_DESVINCULAR_PERSONAL, 
    VISTA_EXITO_DESVINCULAR_PERSONAL, 
    VISTA_FALLO_DESVINCULAR_PERSONAL,

    CONSULTAR_PERSONAL_POR_ID, 
    VISTA_CONSULTAR_PERSONAL_POR_ID, 
    VISTA_RESULTADO_CONSULTAR_PERSONAL_POR_ID,

    CONSULTAR_PERSONAL_EXISTENTE,
    VISTA_RESULTADO_CONSULTAR_PERSONAL_EXISTENTE,

    MODIFICAR_PERSONAL, 
    VISTA_MODIFICAR_PERSONAL, 
    VISTA_EXITO_MODIFICAR_PERSONAL, 
    VISTA_FALLO_MODIFICAR_PERSONAL,
    
    CONSULTAR_PERSONAL_POR_HANGAR, 
    VISTA_CONSULTAR_PERSONAL_POR_HANGAR, 
    VISTA_RESULTADO_CONSULTAR_PERSONAL_POR_HANGAR
   
}
