package presentacion.controlador;

public enum EventosControlador {

	// VISTA GENERAL
	VISTA_PRINCIPAL,

	// VISTA MODELO
	VISTA_MODELO, VISTA_ALTA_MODELO, VISTA_BAJA_MODELO, VISTA_CONSULTAR_MODELO_POR_ID, VISTA_MODIFICAR_MODELO, VISTA_VINCULAR_MODELO, VISTA_DESVINCULAR_MODELO,

	// MODELO
	ALTA_MODELO, BAJA_MODELO, CONSULTAR_MODELO_POR_ID, CONSULTAR_TODOS_MODELOS, MODIFICAR_MODELO, VINCULAR_MODELO, DESVINCULAR_MODELO,

	// VISTA AVIÓN
	VISTA_AVION, VISTA_ALTA_AVION, VISTA_BAJA_AVION, VISTA_CONSULTAR_AVION_POR_ID, VISTA_CONSULTAR_TODOS_AVIONES, VISTA_MODIFICAR_AVION, VISTA_MOSTRAR_AVIONES_POR_MODELO, VISTA_MOSTRAR_AVIONES_POR_AEROLINEA, VISTA_MOSTRAR_AVIONES_POR_HANGAR,

	// AVIÓN
	ALTA_AVION, BAJA_AVION, CONSULTAR_AVION_POR_ID, CONSULTAR_TODOS_AVIONES, MODIFICAR_AVION, MOSTRAR_AVIONES_POR_MODELO, MOSTRAR_AVIONES_POR_AEROLINEA, MOSTRAR_AVIONES_POR_HANGAR,

	// VISTA AEROLÍNEA
	VISTA_AEROLINEA, VISTA_ALTA_AEROLINEA, VISTA_BAJA_AEROLINEA, VISTA_CONSULTAR_AEROLINEA_POR_ID, VISTA_MODIFICAR_AEROLINEA,

	// AEROLÍNEA
	ALTA_AEROLINEA, BAJA_AEROLINEA, CONSULTAR_AEROLINEA_POR_ID, CONSULTAR_TODOS_AEROLINEAS, MODIFICAR_AEROLINEA,

	// VISTA CONTRATO
	VISTA_CONTRATO, VISTA_CARRITO, VISTA_ABRIR_CONTRATO, VISTA_ANYADIR_HANGAR_AL_CONTRATO, VISTA_ELIMINAR_HANGAR_DEL_CONTRATO, VISTA_CONSULTAR_CONTRATO_POR_ID, VISTA_CONSULTAR_TODOS_CONTRATOS, VISTA_MODIFICAR_CONTRATO, VISTA_MODIFICAR_LINEA_CONTRATO, VISTA_MOSTRAR_CONTRATOS_POR_AEROLINEA,

	// CONTRATO
	ABRIR_CONTRATO, CERRAR_CONTRATO, CONSULTAR_CONTRATO_POR_ID, CONSULTAR_TODOS_CONTRATOS, MODIFICAR_CONTRATO, MODIFICAR_LINEA_CONTRATO, MOSTRAR_CONTRATOS_POR_AEROLINEA,

	// VISTA HANGAR
	VISTA_HANGAR, VISTA_ALTA_HANGAR, VISTA_BAJA_HANGAR, VISTA_CONSULTAR_HANGAR_POR_ID, VISTA_MODIFICAR_HANGAR,

	// HANGAR
	ALTA_HANGAR, BAJA_HANGAR, CONSULTAR_HANGAR_POR_ID, CONSULTAR_TODOS_HANGARES, MODIFICAR_HANGAR,

	// VISTA PERSONAL
	VISTA_PERSONAL, VISTA_ALTA_PERSONAL, VISTA_BAJA_PERSONAL, VISTA_VINCULAR_PERSONAL, VISTA_DESVINCULAR_PERSONAL, VISTA_CONSULTAR_PERSONAL_POR_ID, VISTA_MODIFICAR_PERSONAL,

	// PERSONAL
	ALTA_PERSONAL, BAJA_PERSONAL, VINCULAR_PERSONAL, DESVINCULAR_PERSONAL, CONSULTAR_PERSONAL_POR_ID, CONSULTAR_PERSONAL_EXISTENTE, MODIFICAR_PERSONAL
}
